import './globals.css'
import { Poppins } from 'next/font/google'
import LayoutWrapper from '@/components/Layout/LayoutWrapper'
import { WithChildren } from '@/types/common'
import ThemeProvider from '@/components/ThemeProvider'

const poppins = Poppins({ subsets: ['latin'], weight : ["400"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: WithChildren) {
  const { children } = props
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <ThemeProvider attribute="class" defaultTheme='system' enableSystem>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}
